global_currency_parity_exchange_rates_sync:
  cron: '0 12-21 * * *'
  class: Global::CurrencyParityExchangeRates::SyncJob
  queue: global_currency_parity_exchange_rates_sync

global_assets_sync:
  cron: '0 12-21 * * *'
  class: Global::Assets::SyncJob
  queue: global_assets_sync

global_assets_sync_retry:
  cron: '20 12-21 * * *'
  class: Global::Assets::SyncRetryJob
  queue: global_assets_sync_retry

global_rebalance_orders_process:
  cron: '25,30,35,40,45,50,55 12-21 * * *'
  class: Global::RebalanceOrders::ProcessJob
  queue: global_rebalance_orders_process

global_investment_portfolio_rebalance_notification_orders_notification: 
  cron: '0,5,10,15,20,25,30,35,40,45,50,55 12-21 * * *'
  class: Global::InvestmentPortfolioRebalanceNotificationOrders::NotificationJob
  queue: global_investment_portfolio_rebalance_notification_orders_notification